<xsl:stylesheet version="2.0" 
    xmlns:html="http://www.w3.org/TR/REC-html40"
    xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
    xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
	xmlns:video="http://www.google.com/schemas/sitemap-video/1.1"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
<xsl:template match="/">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title>XML Sitemap</title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<style type="text/css">
			body {
				font-family: Helvetica, Arial, sans-serif;
				font-size: 13px;
				color: #545353;
			}
			table {
				border: none;
				border-collapse: collapse;
				text-align: center;
			}
			#sitemap tr.odd {
				background-color: #eee;
			}
			#sitemap tbody tr:hover {
				background-color: #ccc;
			}
			#sitemap tbody tr:hover td, #sitemap tbody tr:hover td a {
				color: #000;
			}
			#content {
				margin: 25px auto;
				text-align: center;
			}
			p.expl {
				margin: 10px 3px;
				line-height: 1.3em;
			}
			p.expl a {
				color: #da3114;
				font-weight: bold;
			}
			a {
				color: #000;
				text-decoration: none;
			}
			a:visited {
				color: #777;
			}
			a:hover {
				text-decoration: underline;
			}
			td {
				font-size:11px;
				padding: 5px 15px 5px 0;
				vertical-align: top;
				text-align: center;
			}
			th {
				text-align:center;
				padding-right:30px;
				font-size:11px;
			}
			thead th {
				border-bottom: 1px solid #000;
				cursor: pointer;
			}
			#sitemap tr:nth-child(even){background-color: #f2f2f2;}		
		</style>
	</head>
	<body>
		<div id="content">
			<h1>XML Sitemap</h1>
			<p class="expl">
				Generated by <a href="https://udinra.com/">Udinra</a>'s <a href="https://udinra.com/downloads/udinra-sitemap-pro/">Udinra Sitemap plugin</a>, this is an XML Sitemap, meant for consumption by Search Engines.
			</p>
			<h3 class="stats">
				This sitemap contains <xsl:value-of select="count(sitemap:urlset/sitemap:url)"/> URLs , <xsl:value-of select="count(sitemap:urlset/sitemap:url/image:image)"/> images and <xsl:value-of select="count(sitemap:urlset/sitemap:url/video:video)"/> videos.
			</h3>			
			<div id="sitemapcontent" style="overflow-x:auto;">
				<table id="sitemap" style="width:1500px">
				<thead>
					<tr>
						<th style="width:10%">URL</th>
						<th style="width:35%">
							<table style="width:100%">
								<tbody>
									<tr>
										<td style="width:40%"><b>Image location</b></td>
										<td style="width:30%"><b>Image Caption</b></td>
										<td style="width:30%"><b>Image Title</b></td>
									</tr>
								</tbody>
							</table>
						</th>
						<th style="width:55%">
							<table style="width:100%">
								<tbody>
									<tr>
										<td style="width:20%"><b>Video Location</b></td>
										<td style="width:15%"><b>Video Title</b></td>
										<td style="width:25%"><b>Video Description</b></td>
										<td style="width:25%"><b>Video Thumbnail</b></td>
										<td style="width:5%"><b>Video Duration</b></td>
										<td style="width:10%"><b>Video Date</b></td>
									</tr>
								</tbody>
							</table>
						</th>
					</tr>
				</thead>
				<tbody>
					<xsl:for-each select="sitemap:urlset/sitemap:url">
						<tr>
							<td  style="width:10%">
								<xsl:variable name="itemURL">
									<xsl:value-of select="sitemap:loc"/>
								</xsl:variable>
								<a href="{$itemURL}">
									<strong><xsl:value-of select="sitemap:loc"/></strong>
								</a>
							</td>
							<td  style="width:35%"><table>
								<xsl:for-each select="image:image">
								<tr>
									<td style="width:40%">
										<xsl:value-of select="image:loc"/>
									</td>
									<td style="width:30%">
										<xsl:variable name="capt">
											<xsl:value-of select="image:caption"/>
										</xsl:variable>      
										<xsl:choose>
											<xsl:when test="string-length($capt) &lt; 200">
												<xsl:value-of select="$capt"/>
											</xsl:when>
											<xsl:otherwise>
												<xsl:value-of select="concat(substring($capt,1,200),' ...')"/>
											</xsl:otherwise>
										</xsl:choose>
									</td>
									<td style="width:30%">
										<xsl:variable name="titl">
											<xsl:value-of select="image:title"/>
										</xsl:variable>      
										<xsl:choose>
											<xsl:when test="string-length($titl) &lt; 200">
												<xsl:value-of select="$titl"/>
											</xsl:when>
											<xsl:otherwise>
												<xsl:value-of select="concat(substring($titl,1,200),' ...')"/>
											</xsl:otherwise>
										</xsl:choose>
									</td>
								</tr>
								</xsl:for-each>
								</table>
							</td>
							<td style="width:55%"><table>
								<xsl:for-each select="video:video">
								<tr>
									<td style="width:20%">
										<xsl:value-of select="video:content_loc"/>
									</td>
									<td style="width:15%">
										<xsl:variable name="capt">
											<xsl:value-of select="video:title"/>
										</xsl:variable>      
										<xsl:choose>
											<xsl:when test="string-length($capt) &lt; 200">
												<xsl:value-of select="$capt"/>
											</xsl:when>
											<xsl:otherwise>
												<xsl:value-of select="concat(substring($capt,1,200),' ...')"/>
											</xsl:otherwise>
										</xsl:choose>
									</td>
									<td style="width:25%">
										<xsl:variable name="titl">
											<xsl:value-of select="video:description"/>
										</xsl:variable>      
										<xsl:choose>
											<xsl:when test="string-length($titl) &lt; 200">
												<xsl:value-of select="$titl"/>
											</xsl:when>
											<xsl:otherwise>
												<xsl:value-of select="concat(substring($titl,1,200),' ...')"/>
											</xsl:otherwise>
										</xsl:choose>
									</td>
									<td style="width:25%">
										<xsl:value-of select="video:thumbnail_loc"/>
									</td>
									<td style="width:5%">
										<xsl:value-of select="video:duration"/>
									</td>
									<td style="width:10%">
										<xsl:value-of select="video:publication_date"/>
									</td>											
								</tr>	
								</xsl:for-each>
								</table>
							</td>
						</tr>
					</xsl:for-each>
				</tbody>
			</table>
		</div>
	</div>
</body>
</html>
</xsl:template>

</xsl:stylesheet>
